#define             VOID            1
#define             VAR             2
#define             CONST           3
#define             IF              4
#define             ELSE            5
#define             WHILE           6
#define             PRINT           7
#define             READ            8
#define             ID              9
#define             INTLITERAL      10
#define             STRING          11
#define             SEMICOLON       12
#define             COMMA           13
#define             PLUSOP          14
#define             MINUSOP         15
#define             PRODOP          16
#define             UNDEROP         17
#define             EQUALOP         18
#define             LPAREN          19
#define             RPAREN          20
#define             LKEY            21
#define             RKEY            22